---
language: python
python: "2.7"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
    - os: linux
      dist: xenial
      sudo: true


services:
  - docker

install:
  - pip install --upgrade pip
  - curl https://raw.githubusercontent.com/timorunge/docker-test-runner/master/install.sh | sh

script:
  - ./docker_test_runner.py 
