---

- name: Install venv using pip
  pip:
    name: virtualenv

- name: Create superset group
  group:
    name: "{{ superset_group }}"

- name: Create superset user
  user:
    name: "{{ superset_user }}"
    group: "{{ superset_group }}"
    home: "{{ superset_homedir }}"

- name: Install superset dependencies:
  pip:
    name: "{{ item }}"
    virtualenv: "{{ superset_venv_path }}"
  loop: "{{ superset_dependencies | flatten(levels=1) }}"

- name: Install superset in venv
  pip:
    name: superset
    virtualenv: "{{ superset_venv_path }}"

