---

- name: Install venv using pip
  pip:
    name: virtualenv

- name: Create superset group
  group:
    name: "{{ superset_group }}"

- name: Create superset user
  user:
    name: "{{ superset_user }}"
    group: "{{ superset_group }}"
    home: "{{ superset_homedir }}"

- name: Install needed packages
  apt:
    name: "{{ item }}"
  loop: "{{ superset_dependencies | flatten(levels=1) }}"

- name: Install PIP superset dependencies
  pip:
    name: "{{ item.key }}"
    virtualenv: "{{ superset_venv_path }}"
    version: "{{ item.value }}"
  loop: "{{ superset_pip_dependencies | dict2items }}"

- name: Install superset in venv
  pip:
    name: superset
    virtualenv: "{{ superset_venv_path }}"

